lua/ide/init.lua, lua/ide/workspaces/workspace_controller.lua
Fixes #14 by implementing a configuration option that enables/disables an autocmd for automatically closing nvim if all remaining windows are components.
=> Implement auto-close

lua/ide/components/outline/component.lua
=> check if textDocument/documentSymbol is supported before using it

.luacheckrc, lua/ide/workspaces/workspace_controller.lua
Fixes #49 
It was checking `VimEnter`, but if we're lazy loading the plugin, the plugin will never see that event because it's already fired by the time the plugin is loaded.
=> fix lazy-loading by checking if we're already past the 'VimEnter' event

README.md, doc/nvim-ide.txt, lua/ide/init.lua, lua/ide/workspaces/workspace_controller.lua
Removes auto_close including docs.
Keeps the config being passed in to WorkspaceController.
=> Remove auto_close

doc/nvim-ide.txt, lua/ide/components/explorer/component.lua
creating a file within the explorer now immediately opens it for editing.
Signed-off-by: Louis DeLosSantos <louis.delos@gmail.com>
=> explorer: open file for editing on create

lua/ide/lib/async_client.lua, lua/ide/lib/git/client.lua
this commit fixes the git client such that errors will now be displayed as vim.notify output.
Signed-off-by: Louis DeLosSantos <louis.delos@gmail.com>
=> useability: expose git errors to vim.notify

README.md, doc/nvim-ide.txt, lua/ide/components/bufferlist/component.lua, lua/ide/init.lua, lua/ide/lib/buf.lua
Currently there is no indicator in bufferlist of which buffer are you currently in.
This commit floats the current buffer up to the top, and places an asterisk to indicate its the current buffer.
Signed-off-by: Louis DeLosSantos <louis.delos@gmail.com>
=> bufferlist: float the current buffer to top of list and track current buffer

doc/nvim-ide.txt
I was looking over the docs earlier, and noticed that the code blocks weren't highlighted like I've seen in other plugins' docs. I changed the markdown code fences to vimdoc's syntax which fixes that.
I also added a modeline I copied from another plugin at the bottom so editing it treats it as a help file.
=> Replace markdown-style code fences with vim help code blocks

README.md
Added an basic example for Packer.nvim installation. Also added a link to the github page for the vim-plug example.
=> Doc: Add Packer.nvim installation example 

lua/ide/components/bookmarks/component.lua
Mentioned in #22 
The NVim default config path in Windows is `~\AppData\Local\nvim`
=> fix: Bookmarks path error in Windows

lua/ide/workspaces/workspace_controller.lua
Turns out this escape is needed. It's a Vim regex, but still a regex, where `.` means "any character", meaning that my repo in under `~/git/github/` does not load the plugin because its matching `/git/` when it should only be matching `/.git/`
=> escape dot in regex

lua/ide/panels/panel.lua
=> panel: prevent other buffers from taking over an ide component's window

lua/ide/components/changes/component.lua
Fixes #82 
These autocmd events I think accomplish the same thing you were trying to do.
=> fix,changes: change autocmd events to avoid cursor flashing

lua/ide/components/explorer/component.lua, lua/ide/panels/panel.lua
In the UI, if a dir is open, register an fs_event_t for it and refresh the UI if external fs events.
Unregister it on dir node collapses.
Signed-off-by: Louis DeLosSantos <louis.delos@gmail.com>
=> feat,explorer: use fs_event_t to display external fs events for open

lua/ide/panels/panel.lua
@ldelossa how about this? just specifically ignoring terminal components when locking.
Fixes #88
=> lock components to windows

lua/ide/components/branches/component.lua, lua/ide/components/explorer/component.lua
1. The filename is matched as lua string pattern. One issue can be seen by creating a file ".~" in the root as following,
```
test@Ross1P:~/start/nvim-ide$ touch .~
Error executing vim.schedule lua callback: ...site/pack/packer/start/nvim-ide/lua/ide/panels/panel.lua:95: Vim(append):Error executing lua callback: Vim:E874: (NFA) Could not pop the stack!
stack traceback:
[C]: in function 'match'
...start/nvim-ide/lua/ide/components/explorer/component.lua:570: in function 'recursive_expand'
...start/nvim-ide/lua/ide/components/explorer/component.lua:563: in function 'recursive_expand'
...start/nvim-ide/lua/ide/components/explorer/component.lua:598: in function 'expand_to_file'
...start/nvim-ide/lua/ide/components/explorer/component.lua:627: in function …
```
=> Fix explorer tree issues

doc/tags
Remove the duplicate 'ide-components' tag. Package managers such as lazy.nvim (https://github.com/folke/lazy.nvim) complain about this duplicate tag when the plugin is installed
=> Remove duplicate tag

lua/ide/components/explorer/component.lua
1. self.expand is called wrongly in previous change
2. expand creates fs_event watch, while it is not removed when collapsing. Remove that. (else, try expanding .git folder and collapse it, while the current file is in another folder. Going to the file would also open the .git folder)
=> Fix a wrong function call in previous merge

lua/ide/buffers/doomscrollbuffer.lua, lua/ide/panels/panel.lua
Here are the changes, and it fixes all the size issues that I have seen,
1. Added winsize_debug logging function to investigate panel size issues (default is off, debug_winsize = false)
2. When component is attached, fix its width if it is left/right. Fix its height if it is top/bottom
3. old_layout needs to do a deep copy to the self.layout (instead of aliasing assignment)
4. self.layout needs to be cleaned before attaching components (I saw like 60s items in it)
5. self.equal needs to put the restore function in reverse to the list, so that their effects are reverted in reversed order (otherwise the state would be incorrect)
6. normalize_panels resized height of bottom panel, even its winfixheight is set to true. Do a resize again after normalizing
Lastly, it also fixes,
1. …
=> Fix panel size issue

doc/nvim-ide.txt
Hey there, thanks for this sweet plugin!
I'm trying to add it to my nixos config without using Packer, but the `buildVimPlugin` helper that nixpkgs uses chokes with
```
E154: Duplicate tag "ide-components" in file /nix/store/g54plhkm0r8i7lipjvybfq77vcfnc805-vimplugin-nvim-ide/./doc/nvim-ide.txtFailed to build help tags!
```
This seems to be happening because the link to the `ide-components` section is using `*asterisks*` instead of `|pipes|`, so its actually defining the tag instead of linking to it. Or at least, that's what I gather from a quick google - I've never tried writing docs for a vim plugin before.
At any rate, if I point my nix config at the commit from this PR, it stops yelling at me :smile:
=> fix(docs): use |link| syntax to link to ide-components tag

doc/nvim-ide.txt
Presets is located at `lua/ide/components/explorer/presets.lua`. The current docs are having an incorrect path.
=> fix(docs) : Update Module Path in Explorer Presets Documentation
